FROM node:22.12.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production

COPY . .

RUN npm run build

COPY prod.env /app/prod.env

# CMD ["node", "dist/main.js"]

# 핫리로드용 실행 커맨드 (개발용)
CMD ["npm", "run", "start:dev"]