FROM node:22.12.0-alpine

WORKDIR /usr/src/app

# package.json과 package-lock.json 복사 후 의존성 설치 (production only)
COPY package*.json ./

RUN npm install --production

# 소스 전체 복사
COPY . .

# 빌드 (ts -> js 컴파일)
RUN npm run build

COPY prod.env /app/prod.env

# 앱 실행
# CMD ["node", "dist/main.js"]

# 핫리로드용 실행 커맨드 (개발용)
CMD ["npm", "run", "start:dev"]