@startuml RegisterReward

actor User
participant GatewayServer
participant AuthServer
participant EventServer
participant MongoDB

== 보상 등록 요청 ==

User -> GatewayServer : 보상 등록 요청 (JWT 포함, 보상 데이터)
activate GatewayServer
GatewayServer -> AuthServer : JWT 검증 + Role(OPERATOR / ADMIN) 확인
deactivate GatewayServer
activate AuthServer

alt 역할이 OPERATOR 또는 ADMIN 아님
    AuthServer --> GatewayServer : 권한 부족 응답
    activate GatewayServer

    GatewayServer --> User : 보상 등록 실패 (권한 부족)
    deactivate GatewayServer
else 역할이 유효함
    AuthServer --> GatewayServer : 검증 성공
    deactivate AuthServer
    activate GatewayServer

    GatewayServer -> EventServer : 보상 등록 요청 (보상 데이터)
    deactivate GatewayServer
    activate EventServer

    EventServer -> MongoDB : 보상 정보 저장
    deactivate EventServer
    activate MongoDB
    alt DB 저장 실패
        MongoDB --> EventServer : 저장 실패
        activate EventServer

        EventServer --> GatewayServer : 등록 실패
        deactivate EventServer
        activate GatewayServer

        GatewayServer --> User : 보상 등록 실패 (DB 오류)
        deactivate GatewayServer
    else 저장 성공
        MongoDB --> EventServer : 저장 완료
        deactivate MongoDB
        activate EventServer

        EventServer --> GatewayServer : 등록 성공
        deactivate EventServer
        activate GatewayServer

        GatewayServer --> User : 등록 성공
        deactivate GatewayServer
    end
end

@enduml
