@startuml UserRegister

actor User
participant GatewayServer
participant AuthServer
participant MongoDB

== 유저 등록 시퀀스 ==

User -> GatewayServer : 유저 등록 요청 (username, 비밀번호 등)
activate GatewayServer

GatewayServer -> AuthServer : 유저 등록 요청 (username, 비밀번호 등)
deactivate GatewayServer
activate AuthServer

alt 유저 정보 저장 성공
    AuthServer -> MongoDB : 유저 정보 저장 (username, 비밀번호 등)
    deactivate AuthServer
    activate MongoDB
    MongoDB --> AuthServer : 유저 저장 완료
    deactivate MongoDB
    activate AuthServer

    AuthServer --> GatewayServer : 유저 등록 성공 응답
    activate GatewayServer

    GatewayServer --> User : 유저 등록 완료
    deactivate GatewayServer
else 유저 정보 저장 실패
    alt 중복된 UsecaseStereotypeFontName
        AuthServer --> GatewayServer : 유저 등록 실패 응답 (중복된 username)
        activate GatewayServer
    else DB 연결 실패
        AuthServer --> GatewayServer : 유저 등록 실패 응답 (DB 연결 오류)
    end
    deactivate AuthServer
    activate GatewayServer

    GatewayServer --> User : 유저 등록 실패
    deactivate GatewayServer
end

@enduml
